name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Ensure Docker & Docker Compose are installed
            sudo apt update
            sudo apt install -y docker.io git

            # Install Docker Compose if not already installed
            if ! command -v docker-compose &> /dev/null
            then
                echo "Docker Compose not found, installing..."
                sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            # Navigate to project directory or clone if it doesn't exist
            if [ ! -d "~/fastapi-book-project" ]; then
              git clone https://github.com/ChinonsoNwakudu/fastapi-book-project.git ~/fastapi-book-project
            fi
            
            cd ~/fastapi-book-project
            git fetch origin main
            git reset --hard origin/main

            # Restart the application
            sudo docker-compose down
            sudo docker-compose up -d --build

            # Check running containers
            sudo docker ps -a
